/*let cambalhota = 1
while (cambalhota <= 10) {

    console.log(`Cambalhota do Bryan ${cambalhota}`)
    cambalhota++

}
console.log('Acabou ' + cambalhota)*/

/*let contadora = 1

do {

    console.log(`cambalhota ${contadora}`)
    contadora++
}
while (contadora < 1)
console.log(contadora)*/

/*let salario = 500

do {
    console.log('O salário ainda é ' + salario)
    salario = salario + 100 // salario += 100

} while (salario < 1000)

console.log(salario)
    //600
    //700
    //800
    //900
    //1000*/

let contagem = 0
while (contagem <= 100) {
    console.log(`Contando ${contagem}`)
    contagem++
}
console.log('Acabou a contagem. ')